### ISSUE TITLE
Items in the same position from another page are using settings from another page (when its permisson is set)

### ISSUE THREAD

**Issue by TomLewis** [MineVid/dtlTraders-plus-#6]
This one is a little difficult to explain.

I have 2 pages, the first page I have 1 item in the centre of the GUI.
On the second page, I have an item in the centre of a GUI.

I changed the first-page permission to something else to "hide" it from other players, so I didn't need to delete the page contents.

But for some reason, when I buy from the second-page item, it's using the details of the first-page item.

I set the user limit to 5x limit for my first page Item which I set the permission on the page.
But no matter what I set the second page Item user limit as, it kept picking up the first page limit.

The only way I found how to solve this was to delete the entire shop, then save it to disk, then load it from disk and reload the plugin, then create a new shop.

**Comment by MinevidOld** [comment]
are the two items the same? (not talking about pricing and so)

**Comment by TheKissay** [comment]
Hi! I have the same problem and I can contribute to localize the bug.

When I setup two or more pages in one store and set the permission of first page to not appear, the shop loads the GUI of the second page but the "logic" of the first page, and when the user changes to the next page, the shop loads "the logic" and the GUI of the correct page and the bug dissapear.

For example:

1º Create three pages of one shop, the first page must have a permission and the user must set said permission to false
![imagen](https://user-images.githubusercontent.com/64664051/133103123-84e7ef37-ef7f-4b29-9842-4e917cca72df.png)
(the first page has the permission "test.test"
![imagen](https://user-images.githubusercontent.com/64664051/133103271-4cafe315-a250-4d60-9f91-309e191c3bb4.png)

2º Fill the first and the second pages with items for trade (not neccesary must be the same item, or be in the same slot)
![imagen](https://user-images.githubusercontent.com/64664051/133103783-dbee211c-2864-48c1-a23e-30b79b9ec529.png)
(first page)
![imagen](https://user-images.githubusercontent.com/64664051/133103851-090bd51b-92e1-4285-aed2-aefef0d4e5b9.png)
(second page)
![imagen](https://user-images.githubusercontent.com/64664051/133104020-bd6fc990-0a6c-46a8-bb20-afcaee63c77a.png)
(third page)

3º When I open the shop for trade anything, the GUI is of the second page because i has setted the permission "test.test" to false and the first page was blocked, but I can't trade the item of the second page.
![imagen](https://user-images.githubusercontent.com/64664051/133104758-937234b9-5248-4304-a4e8-3d43237e75c8.png)
But if i click on the another slot, which is where the item of the first page was, i can trade it.
![imagen](https://user-images.githubusercontent.com/64664051/133105404-b3bdf8f4-5e50-48e1-bc0e-623b8a94be65.png)

4º If i try to switch to the third page, the GUI of the second page keeps, but the "logic" changes to the second page and i can trade the correct item for the second page, and the bug dissapear.
![imagen](https://user-images.githubusercontent.com/64664051/133105732-f919901c-dfc7-4aa4-9ea4-87f16cac485b.png)

This is the output of the /dtl info
![imagen](https://user-images.githubusercontent.com/64664051/133105832-755975f0-0ba5-402f-ad62-3ca73ab80a4d.png)

And this is the dtlTradersPlus config folder that i created for this example.
[dtlTradersPlus.zip](https://github.com/MineVid/dtlTraders-plus-/files/7155184/dtlTradersPlus.zip)

**Comment by MinevidOld** [comment]
Test the newest version. It should be fixed
